version: '3.8'
services:
  corplus:
    image: ghcr.io/cjvtul/corplus-concordancer:prod
    container_name: corplus
    restart: always
    volumes:
      - ./import:/app/import
    environment:
      - CORPLUS_DATABASE_URL=postgres://postgres:postgres@postgres:5432/corplus-concordancer
    ports:
      - "3030:3000"
    depends_on:
      - postgres
    networks:
      - corplus-concordancer-network
  postgres:
    image: postgres:16-alpine
    shm_size: 4g
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=corplus-concordancer
    volumes:
      - postgres-corplus:/var/lib/postgresql/data
    command: [
      "postgres",
      "-c",
      "statement_timeout=60000",
    ]
    networks:
      - corplus-concordancer-network
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/rokurbanc/.docker/config.json:/config.json
    command: --interval 60 --cleanup
volumes:
  postgres-corplus:
    driver: local
networks:
  corplus-concordancer-network:
